instal_pseudo: предупреждение при отсутствии файла
Если при создании псевдомодулей исходный файл для симлинка отсутствует,
печатаем предупреждение в stderr.

Signed-off-by: Alexander Gordeev <lasaine@lvk.cs.msu.su>

diff --git a/install_pseudo b/install_pseudo
--- a/install_pseudo
+++ b/install_pseudo
@@ -14,6 +14,16 @@ choose_chgrp_and_chmod()
   fi
 }
 
+link_safe()
+{
+	#usage: link_safe SOURCE TARGET
+	if [ -e "$1" ]; then
+		ln -s "$1" "$2"
+	else
+		echo "Path $1 not found." >&2
+	fi
+}
+
 # Создание псевдомодуля pccts
 install_pccts()
 {
@@ -26,9 +36,9 @@ install_pccts()
   mkdir $WINAME/bin
   for prog in /usr/bin/antlr /usr/bin/dlg /usr/bin/genmk /usr/bin/sor; do
     link=$(basename "$prog")
-    ln -s "$prog" "$WINAME/bin/$link"
+    link_safe "$prog" "$WINAME/bin/$link"
   done
-  ln -s /usr/include/pccts $WINAME/include
+  link_safe /usr/include/pccts $WINAME/include
   $CHGRP -R $CVSGROUP $WINAME
   $CHMOD -R g+rw $WINAME
 }
@@ -68,11 +78,11 @@ install_Glib2()
   mkdir $WINAME/include $WINAME/lib
   for header in /usr/include/glib-2.0/* /usr/lib/glib-2.0/include/*; do
     link=$(basename "$header")
-    ln -s "$header" "$WINAME/include/$link"
+    link_safe "$header" "$WINAME/include/$link"
   done
   for lib in /usr/lib/libglib-2.0.* /usr/lib/libgmodule-2.0.* /usr/lib/libgobject-2.0.* /usr/lib/libgthread-2.0.*; do
     link=$(basename "$lib")
-    ln -s "$lib" "$WINAME/lib/$link"
+    link_safe "$lib" "$WINAME/lib/$link"
   done
   $CHGRP -R $CVSGROUP $WINAME
   $CHMOD -R g+rw $WINAME
@@ -85,15 +95,15 @@ install_Qt3()
   touch $WINAME/REMOVE_ON_CVSLVK_UPDATE
   touch $WINAME/NOREMOVE
   cp $SOURCE/rules.cvslvk.qt3 $WINAME/rules.cvslvk
-  ln -s /usr/include/qt3 $WINAME/include
+  link_safe /usr/include/qt3 $WINAME/include
   mkdir $WINAME/bin $WINAME/lib
   for prog in /usr/bin/lrelease-qt3 /usr/bin/lupdate-qt3 /usr/bin/moc-qt3 /usr/bin/uic-qt3; do
     link=$(basename "$prog" -qt3)
-    ln -s "$prog" "$WINAME/bin/$link"
+    link_safe "$prog" "$WINAME/bin/$link"
   done
   for lib in /usr/lib/libqt-mt.so /usr/lib/libqt-mt.so.3; do
     link=$(basename "$lib")
-    ln -s "$lib" "$WINAME/lib/$link"
+    link_safe "$lib" "$WINAME/lib/$link"
   done
   $CHGRP -R $CVSGROUP $WINAME
   $CHMOD -R g+rw $WINAME
@@ -106,15 +116,15 @@ install_Qt4()
   touch $WINAME/REMOVE_ON_CVSLVK_UPDATE
   touch $WINAME/NOREMOVE
   cp $SOURCE/rules.cvslvk.qt4 $WINAME/rules.cvslvk
-  ln -s /usr/include/qt4 $WINAME/include
+  link_safe /usr/include/qt4 $WINAME/include
   mkdir $WINAME/bin $WINAME/lib
   for prog in /usr/bin/lrelease-qt4 /usr/bin/lupdate-qt4 /usr/bin/moc-qt4 /usr/bin/uic-qt4 /usr/bin/rcc; do
     link=$(basename "$prog" -qt4)
-    ln -s "$prog" "$WINAME/bin/$link"
+    link_safe "$prog" "$WINAME/bin/$link"
   done
   for lib in /usr/lib/libQt*; do
     link=$(basename "$lib")
-    ln -s "$lib" "$WINAME/lib/$link"
+    link_safe "$lib" "$WINAME/lib/$link"
   done
   $CHGRP -R $CVSGROUP $WINAME
   $CHMOD -R g+rw $WINAME
